name: Create and publish a Docker image to ghcr.io

on:
  push:
    tags:
      - 'v*.*.*'
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  docker:
    name: build and push image to docker hub
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: checkout
      uses: actions/checkout@v4

    - name: prepare
      id: prep
      run: |
        DOCKER_IMAGE="${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}"
        VERSION=latest
        if [[ $GITHUB_REF == refs/tags/* ]]; then
          VERSION=${GITHUB_REF#refs/tags/}
        elif [[ $GITHUB_REF == refs/heads/* ]]; then
          VERSION=$(echo ${GITHUB_REF#refs/heads/} | sed -r 's#/+#-#g')
        elif [[ $GITHUB_REF == refs/pull/* ]]; then
          VERSION=pr-${{ github.event.number }}
        fi
        TAGS="${DOCKER_IMAGE}:${VERSION}"
        #if [ "${{ github.event_name }}" = "push" ]; then
        #  TAGS="$TAGS,${DOCKER_IMAGE}:sha-${GITHUB_SHA::8}"
        #fi
        echo "version=${VERSION}" >> $GITHUB_OUTPUT
        echo "tags=${TAGS}" >> $GITHUB_OUTPUT
        #echo "current_time=$(date -u +'%Y-%m-%dT%H:%M:%SZ')" >> $GITHUB_OUTPUT
        echo "current_time=$(date -u +'%m-%d')" >> $GITHUB_OUTPUT
        echo "git_description=$(git describe --always --dirty --tags --long)" >> $GITHUB_OUTPUT

    - name: Log in to the Container registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: buil and push 
      id: docker_build
      uses: docker/build-push-action@v6
      with:
        context: .
        file: ./deploy/Dockerfile
        push: ${{ github.event_name != 'pull_request' }}
        tags: ${{ steps.prep.outputs.tags }}
        build-args: |
          current_time=${{ steps.prep.outputs.current_time }}
          git_description=${{ steps.prep.outputs.git_description }}

    - name: imge digest
      run: echo ${{ steps.docker_build.outputs.digest }}

    - name: post to set-img webhook
      shell: bash
      env:
        TOKEN: ${{ secrets.GITHUB_TOKEN }}
        URL: ${{ secrets.SET_IMG_URL }}
        USER: ${{ github.actor }}
      run: |
       curl "$URL?user=$USER" \
        -X POST \
        -H "Authorization: $TOKEN" \
        --data-binary '{"namespace":"wu","kind": "sts","name":"pg","container_name":"postgres","img":"${{ steps.prep.outputs.tags }}"}'
